const fs = require("node:fs");
const openapiTS = require("openapi-typescript").default;
const astToString = require("openapi-typescript").astToString;
const simpleGit = require("simple-git");
const PackageJson = require("@npmcli/package-json");

const apis = {
  auth: "https://api.profcomff.com/auth/openapi.json",
  marketing: "https://api.profcomff.com/marketing/openapi.json",
  timetable: "https://api.profcomff.com/timetable/openapi.json",
  services: "https://api.profcomff.com/services/openapi.json",
  print: "https://api.profcomff.com/print/openapi.json",
  social: "https://api.profcomff.com/social/openapi.json",
  userdata: "https://api.profcomff.com/userdata/openapi.json",
  achievement: "https://api.profcomff.com/achievement/openapi.json",
  rating: "https://api.profcomff.com/rating/openapi.json",
  rental: "https://api.profcomff.com/rental/openapi.json",
};

const header = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */`.trim();

/**
 * Добавляет к путям префикс, соответствующий пути к корню API
 */
const updatePathsWithPrefix = (prefix, ast) => {
  for (const i in ast) {
    for (const j in ast[i]["members"]) {
      if (ast[i]["members"][j]["name"]) {
        if (ast[i]["members"][j]["name"]["text"].startsWith("/")) {
          ast[i]["members"][j]["name"]["text"] =
            prefix + ast[i]["members"][j]["name"]["text"];
        }
      }
    }
  }
};

/**
 * Генерирует список путей и интерфейсов
 */
const generate = async () => {
  for (const file in apis) {
    const spec = apis[file];
    const prefix = "/" + file;
    console.log(`Generating ${file} from ${spec}`);

    const ast = await openapiTS(spec, {
      alphabetize: true,
      excludeDeprecated: true,
    });

    updatePathsWithPrefix(prefix, ast);

    const contents = astToString(ast);

    fs.writeFileSync(`./src/openapi/${file}.ts`, header + "\n\n" + contents);
  }
};

/**
 * Проверяет есть ли изменения в репозитории, меняет версию в package-json если да
 */
const updateRepo = async () => {
  const git = simpleGit();

  // Ensure status
  let status = await git.status();
  if (Object.keys(status.modified).length === 0) {
    console.log("Nothing changed");
    return;
  }
  console.log(`${Object.keys(status.modified).length} files changed`);
};

generate().then(() => {
  updateRepo().then(() => {
    console.log("Completed");
  });
});
