/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rating/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Comments
         * @description Scopes: `["rating.comment.review"]`
         *
         *      `limit` - максимальное количество возвращаемых комментариев
         *
         *      `offset` -  смещение, определяющее, с какого по порядку комментария начинать выборку.
         *      Если без смещения возвращается комментарий с условным номером N,
         *      то при значении offset = X будет возвращаться комментарий с номером N + X
         *
         *     `order_by` - возможные значения `"create_ts", "mark_kindness", "mark_freebie", "mark_clarity", "mark_general", "like_diff"`.
         *      Если передано `'create_ts'` - возвращается список комментариев, отсортированных по времени
         *      Если передано `'mark_...'` - возвращается список комментариев, отсортированных по конкретной оценке
         *      Если передано `'like_diff'` - возвращается список комментариев, отсортированных по разнице лайков и дизлайков
         *
         *      `lecturer_id` - вернет все комментарии для преподавателя с конкретным id, по дефолту возвращает вообще все аппрувнутые комментарии.
         *
         *      `user_id` - вернет все комментарии пользователя с конкретным id
         *
         *      `unreviewed` - вернет все непроверенные комментарии, если True. По дефолту False.
         *
         *      `asc_order` -Если передано true, сортировать в порядке возрастания. Иначе - в порядке убывания
         */
        get: operations["get_comments_comment_get"];
        put?: never;
        /**
         * Create Comment
         * @description Создает комментарий к преподавателю в базе данных RatingAPI
         *     Для создания комментария нужно быть авторизованным
         */
        post: operations["create_comment_comment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rating/comment/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Comment
         * @description Возвращает комментарий по его UUID в базе данных RatingAPI
         */
        get: operations["get_comment_comment__uuid__get"];
        put?: never;
        post?: never;
        /**
         * Delete Comment
         * @description Scopes: `["rating.comment.delete"]`
         *
         *     Удаляет комментарий по его UUID в базе данных RatingAPI
         */
        delete: operations["delete_comment_comment__uuid__delete"];
        options?: never;
        head?: never;
        /**
         * Update Comment
         * @description Позволяет изменить свой неанонимный комментарий
         */
        patch: operations["update_comment_comment__uuid__patch"];
        trace?: never;
    };
    "/rating/comment/{uuid}/{reaction}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Like Comment
         * @description Handles like/dislike reactions for a comment.
         *
         *     This endpoint allows authenticated users to react to a comment (like/dislike) or change their existing reaction.
         *     If the user has no existing reaction, a new one is created. If the user changes their reaction, it gets updated.
         *     If the user clicks the same reaction again, the reaction is removed.
         *
         *     Args:
         *         uuid (UUID): The UUID of the comment to react to.
         *         reaction (Reaction): The reaction type (like/dislike).
         *         user (dict): Authenticated user data from UnionAuth dependency.
         *
         *     Returns:
         *         CommentGet: The updated comment with reactions in CommentGet format.
         *
         *     Raises:
         *         ObjectNotFound: If the comment with given UUID doesn't exist.
         */
        put: operations["like_comment_comment__uuid___reaction__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rating/comment/{uuid}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Review Comment
         * @description Scopes: `["rating.comment.review"]`
         *     Проверка комментария и присваивания ему статуса по его UUID в базе данных RatingAPI
         *
         *     `review_status` - возможные значения
         *     `approved` - комментарий одобрен и возвращается при запросе лектора
         *     `dismissed` - комментарий отклонен, не отображается в запросе лектора
         */
        patch: operations["review_comment_comment__uuid__review_patch"];
        trace?: never;
    };
    "/rating/comment/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Comments
         * @description Scopes: `["rating.comment.import"]`
         *     Создает комментарии в базе данных RatingAPI
         */
        post: operations["import_comments_comment_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rating/lecturer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lecturers
         * @description `limit` - максимальное количество возвращаемых преподавателей
         *
         *     `offset` - нижняя граница получения преподавателей, т.е. если по дефолту первым возвращается преподаватель с условным номером N, то при наличии ненулевого offset будет возвращаться преподаватель с номером N + offset
         *
         *     `order_by` - возможные значения `"mark_weighted", "mark_kindness", "mark_freebie", "mark_clarity", "mark_general", "last_name"`.
         *     Если передано `'last_name'` - возвращается список преподавателей отсортированных по алфавиту по фамилиям
         *     Если передано `'mark_...'` - возвращается список преподавателей отсортированных по конкретной оценке
         *     Если передано просто так (или с '+' в начале параметра), то сортирует по возрастанию
         *     С '-' в начале -- по убыванию.
         *
         *     *Пример запросов с этим параметром*:
         *     - `...?order_by=-mark_kindness`
         *     - `...?order_by=mark_freebie`
         *     - `...?order_by=+mark_freebie` (эквивалентно 2ому пункту)
         *
         *     `info` - возможные значения `'comments'`.
         *     Если передано `'comments'`, то возвращаются одобренные комментарии к преподавателю.
         *
         *     `subject`
         *     Если передано `subject` - возвращает всех преподавателей, для которых переданное значение совпадает с одним из их предметов преподавания.
         *     Также возвращает всех преподавателей, у которых есть комментарий с совпадающим с данным subject.
         *
         *     `name`
         *     Поле для ФИО. Если передано `name` - возвращает всех преподователей, для которых нашлись совпадения с переданной строкой
         *
         *     `mark`
         *     Поле для оценки. Если передано, то возвращает только тех преподавателей, для которых средняя общая оценка ('general_mark')
         *     больше, чем переданный 'mark'.
         */
        get: operations["get_lecturers_lecturer_get"];
        put?: never;
        /**
         * Create Lecturer
         * @description Scopes: `["rating.lecturer.create"]`
         *
         *     Создает преподавателя в базе данных RatingAPI
         */
        post: operations["create_lecturer_lecturer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rating/lecturer/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lecturer
         * @description Scopes: `["rating.lecturer.read"]`
         *
         *     Возвращает преподавателя по его ID в базе данных RatingAPI
         *
         *     *QUERY* `info: string` - возможные значения `'comments'`.
         *     Если передано `'comments'`, то возвращаются одобренные комментарии к преподавателю.
         *     Subject лектора возвращшается либо из базы данных, либо из любого аппрувнутого комментария
         */
        get: operations["get_lecturer_lecturer__id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Lecturer
         * @description Scopes: `["rating.lecturer.delete"]`
         */
        delete: operations["delete_lecturer_lecturer__id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Lecturer
         * @description Scopes: `["rating.lecturer.update"]`
         */
        patch: operations["update_lecturer_lecturer__id__patch"];
        trace?: never;
    };
    "/rating/lecturer/import_rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Lecturer Rating
         * @description Scopes: `["rating.lecturer.update_rating"]`
         *
         *     Обновляет рейтинг преподавателя в базе данных RatingAPI
         */
        patch: operations["update_lecturer_rating_lecturer_import_rating_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CommentGet */
        CommentGet: {
            /**
             * Create Ts
             * Format: date-time
             */
            create_ts: string;
            /** Dislike Count */
            dislike_count: number;
            /** Lecturer Id */
            lecturer_id: number;
            /** Like Count */
            like_count: number;
            /** Mark Clarity */
            mark_clarity: number;
            /** Mark Freebie */
            mark_freebie: number;
            /** Mark General */
            mark_general: number;
            /** Mark Kindness */
            mark_kindness: number;
            /** Subject */
            subject?: string | null;
            /** Text */
            text: string;
            /**
             * Update Ts
             * Format: date-time
             */
            update_ts: string;
            /** User Id */
            user_id?: number | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
        };
        /** CommentGetAll */
        CommentGetAll: {
            /**
             * Comments
             * @default []
             */
            comments: components["schemas"]["CommentGet"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** CommentGetAllWithAllInfo */
        "CommentGetAllWithAllInfo-Input": {
            /**
             * Comments
             * @default []
             */
            comments: components["schemas"]["CommentGetWithAllInfo"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** CommentGetAllWithAllInfo */
        "CommentGetAllWithAllInfo-Output": {
            /**
             * Comments
             * @default []
             */
            comments: components["schemas"]["CommentGetWithAllInfo"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** CommentGetAllWithStatus */
        "CommentGetAllWithStatus-Input": {
            /**
             * Comments
             * @default []
             */
            comments: components["schemas"]["CommentGetWithStatus"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** CommentGetAllWithStatus */
        "CommentGetAllWithStatus-Output": {
            /**
             * Comments
             * @default []
             */
            comments: components["schemas"]["CommentGetWithStatus"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** CommentGetWithAllInfo */
        CommentGetWithAllInfo: {
            /** Approved By */
            approved_by?: number | null;
            /**
             * Create Ts
             * Format: date-time
             */
            create_ts: string;
            /** Dislike Count */
            dislike_count: number;
            /** Lecturer Id */
            lecturer_id: number;
            /** Like Count */
            like_count: number;
            /** Mark Clarity */
            mark_clarity: number;
            /** Mark Freebie */
            mark_freebie: number;
            /** Mark General */
            mark_general: number;
            /** Mark Kindness */
            mark_kindness: number;
            review_status: components["schemas"]["ReviewStatus"];
            /** Subject */
            subject?: string | null;
            /** Text */
            text: string;
            /**
             * Update Ts
             * Format: date-time
             */
            update_ts: string;
            /** User Id */
            user_id?: number | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
        };
        /** CommentGetWithStatus */
        CommentGetWithStatus: {
            /**
             * Create Ts
             * Format: date-time
             */
            create_ts: string;
            /** Dislike Count */
            dislike_count: number;
            /** Lecturer Id */
            lecturer_id: number;
            /** Like Count */
            like_count: number;
            /** Mark Clarity */
            mark_clarity: number;
            /** Mark Freebie */
            mark_freebie: number;
            /** Mark General */
            mark_general: number;
            /** Mark Kindness */
            mark_kindness: number;
            review_status: components["schemas"]["ReviewStatus"];
            /** Subject */
            subject?: string | null;
            /** Text */
            text: string;
            /**
             * Update Ts
             * Format: date-time
             */
            update_ts: string;
            /** User Id */
            user_id?: number | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
        };
        /** CommentImport */
        CommentImport: {
            /** Create Ts */
            create_ts?: string | null;
            /** Lecturer Id */
            lecturer_id: number;
            /** Mark Clarity */
            mark_clarity?: number;
            /** Mark Freebie */
            mark_freebie?: number;
            /** Mark Kindness */
            mark_kindness?: number;
            /** Subject */
            subject?: string;
            /** Text */
            text?: string;
            /** Update Ts */
            update_ts?: string | null;
        };
        /** CommentImportAll */
        CommentImportAll: {
            /** Comments */
            comments: components["schemas"]["CommentImport"][];
        };
        /** CommentPost */
        CommentPost: {
            /** Create Ts */
            create_ts?: string | null;
            /**
             * Is Anonymous
             * @default true
             */
            is_anonymous: boolean;
            /** Mark Clarity */
            mark_clarity?: number;
            /** Mark Freebie */
            mark_freebie?: number;
            /** Mark Kindness */
            mark_kindness?: number;
            /** Subject */
            subject?: string;
            /** Text */
            text?: string;
            /** Update Ts */
            update_ts?: string | null;
        };
        /** CommentUpdate */
        CommentUpdate: {
            /** Mark Clarity */
            mark_clarity?: number;
            /** Mark Freebie */
            mark_freebie?: number;
            /** Mark Kindness */
            mark_kindness?: number;
            /** Subject */
            subject?: string;
            /** Text */
            text?: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LecturerGet */
        LecturerGet: {
            /** Avatar Link */
            avatar_link?: string | null;
            /** Comments */
            comments?: components["schemas"]["CommentGet"][] | null;
            /** First Name */
            first_name: string;
            /** Id */
            id: number;
            /** Last Name */
            last_name: string;
            /** Mark Clarity Weighted */
            mark_clarity_weighted?: number | null;
            /** Mark Freebie Weighted */
            mark_freebie_weighted?: number | null;
            /** Mark Kindness Weighted */
            mark_kindness_weighted?: number | null;
            /** Mark Weighted */
            mark_weighted?: number | null;
            /** Middle Name */
            middle_name: string;
            /** Rank */
            rank?: number | null;
            /** Subjects */
            subjects?: string[] | null;
            /** Timetable Id */
            timetable_id: number;
            /** Update Ts */
            update_ts?: string | null;
        };
        /** LecturerGetAll */
        LecturerGetAll: {
            /**
             * Lecturers
             * @default []
             */
            lecturers: components["schemas"]["LecturerGet"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** LecturerPatch */
        LecturerPatch: {
            /** Avatar Link */
            avatar_link?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Middle Name */
            middle_name?: string | null;
            /** Timetable Id */
            timetable_id?: number | null;
        };
        /** LecturerPost */
        LecturerPost: {
            /** Avatar Link */
            avatar_link?: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Middle Name */
            middle_name: string;
            /** Timetable Id */
            timetable_id?: number | null;
        };
        /** LecturerUpdateRatingPatch */
        LecturerUpdateRatingPatch: {
            /** Failed */
            failed: number;
            /** Failed Id */
            failed_id: number[];
            /** Updated */
            updated: number;
            /** Updated Id */
            updated_id: number[];
        };
        /** LecturerWithRank */
        LecturerWithRank: {
            /** Avatar Link */
            avatar_link?: string | null;
            /** First Name */
            first_name: string;
            /** Id */
            id: number;
            /** Last Name */
            last_name: string;
            /** Mark Clarity Weighted */
            mark_clarity_weighted: number;
            /** Mark Freebie Weighted */
            mark_freebie_weighted: number;
            /** Mark Kindness Weighted */
            mark_kindness_weighted: number;
            /** Mark Weighted */
            mark_weighted: number;
            /** Middle Name */
            middle_name: string;
            /** Rank */
            rank: number;
            /** Timetable Id */
            timetable_id: number;
            /** Update Ts */
            update_ts?: string | null;
        };
        /**
         * Reaction
         * @enum {string}
         */
        Reaction: "like" | "dislike";
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "approved" | "pending" | "dismissed";
        /** StatusResponseModel */
        StatusResponseModel: {
            /** Message */
            message: string;
            /** Ru */
            ru: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_comments_comment_get: {
        parameters: {
            query?: {
                asc_order?: boolean;
                lecturer_id?: number | null;
                limit?: number;
                offset?: number;
                order_by?: "create_ts" | "mark_kindness" | "mark_freebie" | "mark_clarity" | "mark_general" | "like_diff";
                subject?: string | null;
                unreviewed?: boolean;
                user_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentGetAll"] | components["schemas"]["CommentGetAllWithAllInfo-Output"] | components["schemas"]["CommentGetAllWithStatus-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comment_comment_post: {
        parameters: {
            query: {
                lecturer_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentPost"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comment_comment__uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_comment_comment__uuid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_comment_comment__uuid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    like_comment_comment__uuid___reaction__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reaction: components["schemas"]["Reaction"];
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_comment_comment__uuid__review_patch: {
        parameters: {
            query?: {
                review_status?: "approved" | "dismissed";
            };
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentGetWithAllInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_comments_comment_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentImportAll"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentGetAll"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lecturers_lecturer_get: {
        parameters: {
            query?: {
                info?: "comments"[];
                limit?: number;
                mark?: number;
                name?: string;
                offset?: number;
                order_by?: string | null;
                subject?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturerGetAll"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lecturer_lecturer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LecturerPost"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturerGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lecturer_lecturer__id__get: {
        parameters: {
            query?: {
                info?: "comments"[];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturerGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lecturer_lecturer__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lecturer_lecturer__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LecturerPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturerGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lecturer_rating_lecturer_import_rating_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LecturerWithRank"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturerUpdateRatingPatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
